// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.service;

@com.google.protobuf.Generated
public interface AsyncRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AsyncRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Get topics in given forum.
   * </pre>
   *
   * <code>.TopicListRequest topic_list = 1;</code>
   * @return Whether the topicList field is set.
   */
  boolean hasTopicList();
  /**
   * <pre>
   * Get topics in given forum.
   * </pre>
   *
   * <code>.TopicListRequest topic_list = 1;</code>
   * @return The topicList.
   */
  com.bugenzhao.mnga.protos.service.TopicListRequest getTopicList();
  /**
   * <pre>
   * Get topics in given forum.
   * </pre>
   *
   * <code>.TopicListRequest topic_list = 1;</code>
   */
  com.bugenzhao.mnga.protos.service.TopicListRequestOrBuilder getTopicListOrBuilder();

  /**
   * <pre>
   * Get posts in given topic.
   * </pre>
   *
   * <code>.TopicDetailsRequest topic_details = 2;</code>
   * @return Whether the topicDetails field is set.
   */
  boolean hasTopicDetails();
  /**
   * <pre>
   * Get posts in given topic.
   * </pre>
   *
   * <code>.TopicDetailsRequest topic_details = 2;</code>
   * @return The topicDetails.
   */
  com.bugenzhao.mnga.protos.service.TopicDetailsRequest getTopicDetails();
  /**
   * <pre>
   * Get posts in given topic.
   * </pre>
   *
   * <code>.TopicDetailsRequest topic_details = 2;</code>
   */
  com.bugenzhao.mnga.protos.service.TopicDetailsRequestOrBuilder getTopicDetailsOrBuilder();

  /**
   * <pre>
   * Set filter for subforums.
   * </pre>
   *
   * <code>.SubforumFilterRequest subforum_filter = 3;</code>
   * @return Whether the subforumFilter field is set.
   */
  boolean hasSubforumFilter();
  /**
   * <pre>
   * Set filter for subforums.
   * </pre>
   *
   * <code>.SubforumFilterRequest subforum_filter = 3;</code>
   * @return The subforumFilter.
   */
  com.bugenzhao.mnga.protos.service.SubforumFilterRequest getSubforumFilter();
  /**
   * <pre>
   * Set filter for subforums.
   * </pre>
   *
   * <code>.SubforumFilterRequest subforum_filter = 3;</code>
   */
  com.bugenzhao.mnga.protos.service.SubforumFilterRequestOrBuilder getSubforumFilterOrBuilder();

  /**
   * <pre>
   * Get all forums.
   * </pre>
   *
   * <code>.ForumListRequest forum_list = 4;</code>
   * @return Whether the forumList field is set.
   */
  boolean hasForumList();
  /**
   * <pre>
   * Get all forums.
   * </pre>
   *
   * <code>.ForumListRequest forum_list = 4;</code>
   * @return The forumList.
   */
  com.bugenzhao.mnga.protos.service.ForumListRequest getForumList();
  /**
   * <pre>
   * Get all forums.
   * </pre>
   *
   * <code>.ForumListRequest forum_list = 4;</code>
   */
  com.bugenzhao.mnga.protos.service.ForumListRequestOrBuilder getForumListOrBuilder();

  /**
   * <pre>
   * Find user info remotely.
   * </pre>
   *
   * <code>.RemoteUserRequest remote_user = 5;</code>
   * @return Whether the remoteUser field is set.
   */
  boolean hasRemoteUser();
  /**
   * <pre>
   * Find user info remotely.
   * </pre>
   *
   * <code>.RemoteUserRequest remote_user = 5;</code>
   * @return The remoteUser.
   */
  com.bugenzhao.mnga.protos.service.RemoteUserRequest getRemoteUser();
  /**
   * <pre>
   * Find user info remotely.
   * </pre>
   *
   * <code>.RemoteUserRequest remote_user = 5;</code>
   */
  com.bugenzhao.mnga.protos.service.RemoteUserRequestOrBuilder getRemoteUserOrBuilder();

  /**
   * <pre>
   * Do voting to posts.
   * </pre>
   *
   * <code>.PostVoteRequest post_vote = 6;</code>
   * @return Whether the postVote field is set.
   */
  boolean hasPostVote();
  /**
   * <pre>
   * Do voting to posts.
   * </pre>
   *
   * <code>.PostVoteRequest post_vote = 6;</code>
   * @return The postVote.
   */
  com.bugenzhao.mnga.protos.service.PostVoteRequest getPostVote();
  /**
   * <pre>
   * Do voting to posts.
   * </pre>
   *
   * <code>.PostVoteRequest post_vote = 6;</code>
   */
  com.bugenzhao.mnga.protos.service.PostVoteRequestOrBuilder getPostVoteOrBuilder();

  /**
   * <pre>
   * Get history of visited topics.
   * </pre>
   *
   * <code>.TopicHistoryRequest topic_history = 7;</code>
   * @return Whether the topicHistory field is set.
   */
  boolean hasTopicHistory();
  /**
   * <pre>
   * Get history of visited topics.
   * </pre>
   *
   * <code>.TopicHistoryRequest topic_history = 7;</code>
   * @return The topicHistory.
   */
  com.bugenzhao.mnga.protos.service.TopicHistoryRequest getTopicHistory();
  /**
   * <pre>
   * Get history of visited topics.
   * </pre>
   *
   * <code>.TopicHistoryRequest topic_history = 7;</code>
   */
  com.bugenzhao.mnga.protos.service.TopicHistoryRequestOrBuilder getTopicHistoryOrBuilder();

  /**
   * <pre>
   * Get hot topics in given forum.
   * </pre>
   *
   * <code>.HotTopicListRequest hot_topic_list = 8;</code>
   * @return Whether the hotTopicList field is set.
   */
  boolean hasHotTopicList();
  /**
   * <pre>
   * Get hot topics in given forum.
   * </pre>
   *
   * <code>.HotTopicListRequest hot_topic_list = 8;</code>
   * @return The hotTopicList.
   */
  com.bugenzhao.mnga.protos.service.HotTopicListRequest getHotTopicList();
  /**
   * <pre>
   * Get hot topics in given forum.
   * </pre>
   *
   * <code>.HotTopicListRequest hot_topic_list = 8;</code>
   */
  com.bugenzhao.mnga.protos.service.HotTopicListRequestOrBuilder getHotTopicListOrBuilder();

  /**
   * <pre>
   * Search for a specific forum.
   * </pre>
   *
   * <code>.ForumSearchRequest forum_search = 9;</code>
   * @return Whether the forumSearch field is set.
   */
  boolean hasForumSearch();
  /**
   * <pre>
   * Search for a specific forum.
   * </pre>
   *
   * <code>.ForumSearchRequest forum_search = 9;</code>
   * @return The forumSearch.
   */
  com.bugenzhao.mnga.protos.service.ForumSearchRequest getForumSearch();
  /**
   * <pre>
   * Search for a specific forum.
   * </pre>
   *
   * <code>.ForumSearchRequest forum_search = 9;</code>
   */
  com.bugenzhao.mnga.protos.service.ForumSearchRequestOrBuilder getForumSearchOrBuilder();

  /**
   * <pre>
   * Get favorite topics.
   * </pre>
   *
   * <code>.FavoriteTopicListRequest favorite_topic_list = 10;</code>
   * @return Whether the favoriteTopicList field is set.
   */
  boolean hasFavoriteTopicList();
  /**
   * <pre>
   * Get favorite topics.
   * </pre>
   *
   * <code>.FavoriteTopicListRequest favorite_topic_list = 10;</code>
   * @return The favoriteTopicList.
   */
  com.bugenzhao.mnga.protos.service.FavoriteTopicListRequest getFavoriteTopicList();
  /**
   * <pre>
   * Get favorite topics.
   * </pre>
   *
   * <code>.FavoriteTopicListRequest favorite_topic_list = 10;</code>
   */
  com.bugenzhao.mnga.protos.service.FavoriteTopicListRequestOrBuilder getFavoriteTopicListOrBuilder();

  /**
   * <pre>
   * Mark a topic as favored.
   * </pre>
   *
   * <code>.TopicFavorRequest topic_favor = 11;</code>
   * @return Whether the topicFavor field is set.
   */
  boolean hasTopicFavor();
  /**
   * <pre>
   * Mark a topic as favored.
   * </pre>
   *
   * <code>.TopicFavorRequest topic_favor = 11;</code>
   * @return The topicFavor.
   */
  com.bugenzhao.mnga.protos.service.TopicFavorRequest getTopicFavor();
  /**
   * <pre>
   * Mark a topic as favored.
   * </pre>
   *
   * <code>.TopicFavorRequest topic_favor = 11;</code>
   */
  com.bugenzhao.mnga.protos.service.TopicFavorRequestOrBuilder getTopicFavorOrBuilder();

  /**
   * <pre>
   * Fetch the initial content for a posting action.
   * </pre>
   *
   * <code>.PostReplyFetchContentRequest post_reply_fetch_content = 12;</code>
   * @return Whether the postReplyFetchContent field is set.
   */
  boolean hasPostReplyFetchContent();
  /**
   * <pre>
   * Fetch the initial content for a posting action.
   * </pre>
   *
   * <code>.PostReplyFetchContentRequest post_reply_fetch_content = 12;</code>
   * @return The postReplyFetchContent.
   */
  com.bugenzhao.mnga.protos.service.PostReplyFetchContentRequest getPostReplyFetchContent();
  /**
   * <pre>
   * Fetch the initial content for a posting action.
   * </pre>
   *
   * <code>.PostReplyFetchContentRequest post_reply_fetch_content = 12;</code>
   */
  com.bugenzhao.mnga.protos.service.PostReplyFetchContentRequestOrBuilder getPostReplyFetchContentOrBuilder();

  /**
   * <pre>
   * Do posting to some topic or forum.
   * </pre>
   *
   * <code>.PostReplyRequest post_reply = 13;</code>
   * @return Whether the postReply field is set.
   */
  boolean hasPostReply();
  /**
   * <pre>
   * Do posting to some topic or forum.
   * </pre>
   *
   * <code>.PostReplyRequest post_reply = 13;</code>
   * @return The postReply.
   */
  com.bugenzhao.mnga.protos.service.PostReplyRequest getPostReply();
  /**
   * <pre>
   * Do posting to some topic or forum.
   * </pre>
   *
   * <code>.PostReplyRequest post_reply = 13;</code>
   */
  com.bugenzhao.mnga.protos.service.PostReplyRequestOrBuilder getPostReplyOrBuilder();

  /**
   * <pre>
   * Get all notifications.
   * </pre>
   *
   * <code>.FetchNotificationRequest fetch_notification = 14;</code>
   * @return Whether the fetchNotification field is set.
   */
  boolean hasFetchNotification();
  /**
   * <pre>
   * Get all notifications.
   * </pre>
   *
   * <code>.FetchNotificationRequest fetch_notification = 14;</code>
   * @return The fetchNotification.
   */
  com.bugenzhao.mnga.protos.service.FetchNotificationRequest getFetchNotification();
  /**
   * <pre>
   * Get all notifications.
   * </pre>
   *
   * <code>.FetchNotificationRequest fetch_notification = 14;</code>
   */
  com.bugenzhao.mnga.protos.service.FetchNotificationRequestOrBuilder getFetchNotificationOrBuilder();

  /**
   * <pre>
   * Upload attachments before posting.
   * </pre>
   *
   * <code>.UploadAttachmentRequest upload_attachment = 15;</code>
   * @return Whether the uploadAttachment field is set.
   */
  boolean hasUploadAttachment();
  /**
   * <pre>
   * Upload attachments before posting.
   * </pre>
   *
   * <code>.UploadAttachmentRequest upload_attachment = 15;</code>
   * @return The uploadAttachment.
   */
  com.bugenzhao.mnga.protos.service.UploadAttachmentRequest getUploadAttachment();
  /**
   * <pre>
   * Upload attachments before posting.
   * </pre>
   *
   * <code>.UploadAttachmentRequest upload_attachment = 15;</code>
   */
  com.bugenzhao.mnga.protos.service.UploadAttachmentRequestOrBuilder getUploadAttachmentOrBuilder();

  /**
   * <pre>
   * Get topics of given user.
   * </pre>
   *
   * <code>.UserTopicListRequest user_topic_list = 16;</code>
   * @return Whether the userTopicList field is set.
   */
  boolean hasUserTopicList();
  /**
   * <pre>
   * Get topics of given user.
   * </pre>
   *
   * <code>.UserTopicListRequest user_topic_list = 16;</code>
   * @return The userTopicList.
   */
  com.bugenzhao.mnga.protos.service.UserTopicListRequest getUserTopicList();
  /**
   * <pre>
   * Get topics of given user.
   * </pre>
   *
   * <code>.UserTopicListRequest user_topic_list = 16;</code>
   */
  com.bugenzhao.mnga.protos.service.UserTopicListRequestOrBuilder getUserTopicListOrBuilder();

  /**
   * <pre>
   * Get posts of given user.
   * </pre>
   *
   * <code>.UserPostListRequest user_post_list = 17;</code>
   * @return Whether the userPostList field is set.
   */
  boolean hasUserPostList();
  /**
   * <pre>
   * Get posts of given user.
   * </pre>
   *
   * <code>.UserPostListRequest user_post_list = 17;</code>
   * @return The userPostList.
   */
  com.bugenzhao.mnga.protos.service.UserPostListRequest getUserPostList();
  /**
   * <pre>
   * Get posts of given user.
   * </pre>
   *
   * <code>.UserPostListRequest user_post_list = 17;</code>
   */
  com.bugenzhao.mnga.protos.service.UserPostListRequestOrBuilder getUserPostListOrBuilder();

  /**
   * <pre>
   * Get short message conversations of current user.
   * </pre>
   *
   * <code>.ShortMessageListRequest short_message_list = 18;</code>
   * @return Whether the shortMessageList field is set.
   */
  boolean hasShortMessageList();
  /**
   * <pre>
   * Get short message conversations of current user.
   * </pre>
   *
   * <code>.ShortMessageListRequest short_message_list = 18;</code>
   * @return The shortMessageList.
   */
  com.bugenzhao.mnga.protos.service.ShortMessageListRequest getShortMessageList();
  /**
   * <pre>
   * Get short message conversations of current user.
   * </pre>
   *
   * <code>.ShortMessageListRequest short_message_list = 18;</code>
   */
  com.bugenzhao.mnga.protos.service.ShortMessageListRequestOrBuilder getShortMessageListOrBuilder();

  /**
   * <pre>
   * Get short message posts of a conversation.
   * </pre>
   *
   * <code>.ShortMessageDetailsRequest short_message_details = 19;</code>
   * @return Whether the shortMessageDetails field is set.
   */
  boolean hasShortMessageDetails();
  /**
   * <pre>
   * Get short message posts of a conversation.
   * </pre>
   *
   * <code>.ShortMessageDetailsRequest short_message_details = 19;</code>
   * @return The shortMessageDetails.
   */
  com.bugenzhao.mnga.protos.service.ShortMessageDetailsRequest getShortMessageDetails();
  /**
   * <pre>
   * Get short message posts of a conversation.
   * </pre>
   *
   * <code>.ShortMessageDetailsRequest short_message_details = 19;</code>
   */
  com.bugenzhao.mnga.protos.service.ShortMessageDetailsRequestOrBuilder getShortMessageDetailsOrBuilder();

  /**
   * <pre>
   * Do posting to some short message post or conversation.
   * </pre>
   *
   * <code>.ShortMessagePostRequest short_message_post = 20;</code>
   * @return Whether the shortMessagePost field is set.
   */
  boolean hasShortMessagePost();
  /**
   * <pre>
   * Do posting to some short message post or conversation.
   * </pre>
   *
   * <code>.ShortMessagePostRequest short_message_post = 20;</code>
   * @return The shortMessagePost.
   */
  com.bugenzhao.mnga.protos.service.ShortMessagePostRequest getShortMessagePost();
  /**
   * <pre>
   * Do posting to some short message post or conversation.
   * </pre>
   *
   * <code>.ShortMessagePostRequest short_message_post = 20;</code>
   */
  com.bugenzhao.mnga.protos.service.ShortMessagePostRequestOrBuilder getShortMessagePostOrBuilder();

  /**
   * <pre>
   * Search for topics with some keyword in specific forum or all forums.
   * </pre>
   *
   * <code>.TopicSearchRequest topic_search = 21;</code>
   * @return Whether the topicSearch field is set.
   */
  boolean hasTopicSearch();
  /**
   * <pre>
   * Search for topics with some keyword in specific forum or all forums.
   * </pre>
   *
   * <code>.TopicSearchRequest topic_search = 21;</code>
   * @return The topicSearch.
   */
  com.bugenzhao.mnga.protos.service.TopicSearchRequest getTopicSearch();
  /**
   * <pre>
   * Search for topics with some keyword in specific forum or all forums.
   * </pre>
   *
   * <code>.TopicSearchRequest topic_search = 21;</code>
   */
  com.bugenzhao.mnga.protos.service.TopicSearchRequestOrBuilder getTopicSearchOrBuilder();

  /**
   * <pre>
   * Sign in (clock in) for today.
   * </pre>
   *
   * <code>.ClockInRequest clock_in = 22;</code>
   * @return Whether the clockIn field is set.
   */
  boolean hasClockIn();
  /**
   * <pre>
   * Sign in (clock in) for today.
   * </pre>
   *
   * <code>.ClockInRequest clock_in = 22;</code>
   * @return The clockIn.
   */
  com.bugenzhao.mnga.protos.service.ClockInRequest getClockIn();
  /**
   * <pre>
   * Sign in (clock in) for today.
   * </pre>
   *
   * <code>.ClockInRequest clock_in = 22;</code>
   */
  com.bugenzhao.mnga.protos.service.ClockInRequestOrBuilder getClockInOrBuilder();

  /**
   * <pre>
   * Clear or check the cache.
   * </pre>
   *
   * <code>.CacheRequest cache = 23;</code>
   * @return Whether the cache field is set.
   */
  boolean hasCache();
  /**
   * <pre>
   * Clear or check the cache.
   * </pre>
   *
   * <code>.CacheRequest cache = 23;</code>
   * @return The cache.
   */
  com.bugenzhao.mnga.protos.service.CacheRequest getCache();
  /**
   * <pre>
   * Clear or check the cache.
   * </pre>
   *
   * <code>.CacheRequest cache = 23;</code>
   */
  com.bugenzhao.mnga.protos.service.CacheRequestOrBuilder getCacheOrBuilder();

  /**
   * <pre>
   * List favorite topic folders.
   * </pre>
   *
   * <code>.FavoriteFolderListRequest favorite_folder_list = 24;</code>
   * @return Whether the favoriteFolderList field is set.
   */
  boolean hasFavoriteFolderList();
  /**
   * <pre>
   * List favorite topic folders.
   * </pre>
   *
   * <code>.FavoriteFolderListRequest favorite_folder_list = 24;</code>
   * @return The favoriteFolderList.
   */
  com.bugenzhao.mnga.protos.service.FavoriteFolderListRequest getFavoriteFolderList();
  /**
   * <pre>
   * List favorite topic folders.
   * </pre>
   *
   * <code>.FavoriteFolderListRequest favorite_folder_list = 24;</code>
   */
  com.bugenzhao.mnga.protos.service.FavoriteFolderListRequestOrBuilder getFavoriteFolderListOrBuilder();

  /**
   * <pre>
   * Modify a favorite topic folder.
   * </pre>
   *
   * <code>.FavoriteFolderModifyRequest favorite_folder_modify = 25;</code>
   * @return Whether the favoriteFolderModify field is set.
   */
  boolean hasFavoriteFolderModify();
  /**
   * <pre>
   * Modify a favorite topic folder.
   * </pre>
   *
   * <code>.FavoriteFolderModifyRequest favorite_folder_modify = 25;</code>
   * @return The favoriteFolderModify.
   */
  com.bugenzhao.mnga.protos.service.FavoriteFolderModifyRequest getFavoriteFolderModify();
  /**
   * <pre>
   * Modify a favorite topic folder.
   * </pre>
   *
   * <code>.FavoriteFolderModifyRequest favorite_folder_modify = 25;</code>
   */
  com.bugenzhao.mnga.protos.service.FavoriteFolderModifyRequestOrBuilder getFavoriteFolderModifyOrBuilder();

  /**
   * <pre>
   * Create a favorite topic folder.
   * </pre>
   *
   * <code>.FavoriteFolderCreateRequest favorite_folder_create = 26;</code>
   * @return Whether the favoriteFolderCreate field is set.
   */
  boolean hasFavoriteFolderCreate();
  /**
   * <pre>
   * Create a favorite topic folder.
   * </pre>
   *
   * <code>.FavoriteFolderCreateRequest favorite_folder_create = 26;</code>
   * @return The favoriteFolderCreate.
   */
  com.bugenzhao.mnga.protos.service.FavoriteFolderCreateRequest getFavoriteFolderCreate();
  /**
   * <pre>
   * Create a favorite topic folder.
   * </pre>
   *
   * <code>.FavoriteFolderCreateRequest favorite_folder_create = 26;</code>
   */
  com.bugenzhao.mnga.protos.service.FavoriteFolderCreateRequestOrBuilder getFavoriteFolderCreateOrBuilder();

  /**
   * <pre>
   * Update the signature of the current user.
   * </pre>
   *
   * <code>.UserSignatureUpdateRequest user_signature_update = 27;</code>
   * @return Whether the userSignatureUpdate field is set.
   */
  boolean hasUserSignatureUpdate();
  /**
   * <pre>
   * Update the signature of the current user.
   * </pre>
   *
   * <code>.UserSignatureUpdateRequest user_signature_update = 27;</code>
   * @return The userSignatureUpdate.
   */
  com.bugenzhao.mnga.protos.service.UserSignatureUpdateRequest getUserSignatureUpdate();
  /**
   * <pre>
   * Update the signature of the current user.
   * </pre>
   *
   * <code>.UserSignatureUpdateRequest user_signature_update = 27;</code>
   */
  com.bugenzhao.mnga.protos.service.UserSignatureUpdateRequestOrBuilder getUserSignatureUpdateOrBuilder();

  /**
   * <pre>
   * Get favorite forums (forum_favor2).
   * </pre>
   *
   * <code>.FavoriteForumListRequest favorite_forum_list = 28;</code>
   * @return Whether the favoriteForumList field is set.
   */
  boolean hasFavoriteForumList();
  /**
   * <pre>
   * Get favorite forums (forum_favor2).
   * </pre>
   *
   * <code>.FavoriteForumListRequest favorite_forum_list = 28;</code>
   * @return The favoriteForumList.
   */
  com.bugenzhao.mnga.protos.service.FavoriteForumListRequest getFavoriteForumList();
  /**
   * <pre>
   * Get favorite forums (forum_favor2).
   * </pre>
   *
   * <code>.FavoriteForumListRequest favorite_forum_list = 28;</code>
   */
  com.bugenzhao.mnga.protos.service.FavoriteForumListRequestOrBuilder getFavoriteForumListOrBuilder();

  /**
   * <pre>
   * Add or remove a favorite forum (forum_favor2).
   * </pre>
   *
   * <code>.FavoriteForumModifyRequest favorite_forum_modify = 29;</code>
   * @return Whether the favoriteForumModify field is set.
   */
  boolean hasFavoriteForumModify();
  /**
   * <pre>
   * Add or remove a favorite forum (forum_favor2).
   * </pre>
   *
   * <code>.FavoriteForumModifyRequest favorite_forum_modify = 29;</code>
   * @return The favoriteForumModify.
   */
  com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest getFavoriteForumModify();
  /**
   * <pre>
   * Add or remove a favorite forum (forum_favor2).
   * </pre>
   *
   * <code>.FavoriteForumModifyRequest favorite_forum_modify = 29;</code>
   */
  com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequestOrBuilder getFavoriteForumModifyOrBuilder();

  /**
   * <pre>
   * Query clock-in stats only (no sign-in side effect).
   * </pre>
   *
   * <code>.ClockInStatsRequest clock_in_stats = 30;</code>
   * @return Whether the clockInStats field is set.
   */
  boolean hasClockInStats();
  /**
   * <pre>
   * Query clock-in stats only (no sign-in side effect).
   * </pre>
   *
   * <code>.ClockInStatsRequest clock_in_stats = 30;</code>
   * @return The clockInStats.
   */
  com.bugenzhao.mnga.protos.service.ClockInStatsRequest getClockInStats();
  /**
   * <pre>
   * Query clock-in stats only (no sign-in side effect).
   * </pre>
   *
   * <code>.ClockInStatsRequest clock_in_stats = 30;</code>
   */
  com.bugenzhao.mnga.protos.service.ClockInStatsRequestOrBuilder getClockInStatsOrBuilder();

  /**
   * <pre>
   * Delete the history snapshot of a single topic.
   * </pre>
   *
   * <code>.DeleteTopicHistoryRequest delete_topic_history = 31;</code>
   * @return Whether the deleteTopicHistory field is set.
   */
  boolean hasDeleteTopicHistory();
  /**
   * <pre>
   * Delete the history snapshot of a single topic.
   * </pre>
   *
   * <code>.DeleteTopicHistoryRequest delete_topic_history = 31;</code>
   * @return The deleteTopicHistory.
   */
  com.bugenzhao.mnga.protos.service.DeleteTopicHistoryRequest getDeleteTopicHistory();
  /**
   * <pre>
   * Delete the history snapshot of a single topic.
   * </pre>
   *
   * <code>.DeleteTopicHistoryRequest delete_topic_history = 31;</code>
   */
  com.bugenzhao.mnga.protos.service.DeleteTopicHistoryRequestOrBuilder getDeleteTopicHistoryOrBuilder();

  com.bugenzhao.mnga.protos.service.AsyncRequest.ValueCase getValueCase();
}
