// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.service;

@com.google.protobuf.Generated
public interface DeleteTopicHistoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeleteTopicHistoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Delete the history snapshot of this topic, if any.
   * </pre>
   *
   * <code>string topic_id = 1;</code>
   * @return The topicId.
   */
  java.lang.String getTopicId();
  /**
   * <pre>
   * Delete the history snapshot of this topic, if any.
   * </pre>
   *
   * <code>string topic_id = 1;</code>
   * @return The bytes for topicId.
   */
  com.google.protobuf.ByteString
      getTopicIdBytes();
}
