// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.service;

@com.google.protobuf.Generated
public interface DeleteTopicHistoryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeleteTopicHistoryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool deleted = 1;</code>
   * @return The deleted.
   */
  boolean getDeleted();
}
