// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.service;

@com.google.protobuf.Generated
public final class Service extends com.google.protobuf.GeneratedFile {
  private Service() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "Service");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SyncRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SyncRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConfigureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ConfigureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConfigureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ConfigureResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LocalUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LocalUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LocalUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LocalUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AuthRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AuthResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ContentParseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ContentParseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ContentParseResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ContentParseResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SubjectParseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SubjectParseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SubjectParseResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SubjectParseResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MarkNotificationReadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MarkNotificationReadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MarkNotificationReadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MarkNotificationReadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SetRequestOptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SetRequestOptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SetRequestOptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SetRequestOptionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateTopicProgressRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UpdateTopicProgressRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateTopicProgressResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UpdateTopicProgressResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AsyncRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AsyncRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TopicListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TopicListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TopicListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TopicListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TopicDetailsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TopicDetailsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TopicDetailsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TopicDetailsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SubforumFilterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SubforumFilterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SubforumFilterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SubforumFilterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ForumListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ForumListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ForumListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ForumListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RemoteUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RemoteUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RemoteUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RemoteUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PostVoteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PostVoteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PostVoteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PostVoteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TopicHistoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TopicHistoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TopicHistoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TopicHistoryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteTopicHistoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DeleteTopicHistoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteTopicHistoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DeleteTopicHistoryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HotTopicListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HotTopicListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HotTopicListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HotTopicListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ForumSearchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ForumSearchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ForumSearchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ForumSearchResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FavoriteForumListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FavoriteForumListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FavoriteForumListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FavoriteForumListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FavoriteForumModifyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FavoriteForumModifyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FavoriteForumModifyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FavoriteForumModifyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FavoriteTopicListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FavoriteTopicListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FavoriteTopicListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FavoriteTopicListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FavoriteFolderListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FavoriteFolderListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FavoriteFolderListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FavoriteFolderListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FavoriteFolderModifyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FavoriteFolderModifyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FavoriteFolderModifyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FavoriteFolderModifyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FavoriteFolderCreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FavoriteFolderCreateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FavoriteFolderCreateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FavoriteFolderCreateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TopicFavorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TopicFavorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TopicFavorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TopicFavorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PostReplyFetchContentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PostReplyFetchContentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PostReplyFetchContentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PostReplyFetchContentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PostReplyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PostReplyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PostReplyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PostReplyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FetchNotificationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FetchNotificationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FetchNotificationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FetchNotificationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UploadAttachmentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UploadAttachmentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UploadAttachmentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UploadAttachmentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserTopicListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserTopicListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserTopicListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserTopicListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserPostListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserPostListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserPostListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserPostListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ShortMessageListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ShortMessageListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ShortMessageListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ShortMessageListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ShortMessageDetailsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ShortMessageDetailsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ShortMessageDetailsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ShortMessageDetailsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ShortMessagePostRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ShortMessagePostRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ShortMessagePostResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ShortMessagePostResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserSignatureUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserSignatureUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserSignatureUpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserSignatureUpdateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TopicSearchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TopicSearchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TopicSearchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TopicSearchResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClockInRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClockInRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClockInStatsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClockInStatsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClockInStatsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClockInStatsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClockInResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClockInResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CacheRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CacheRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CacheResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CacheResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InvalidateClientRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_InvalidateClientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InvalidateClientResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_InvalidateClientResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MockApi_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MockApi_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MockApi_TopicList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MockApi_TopicList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MockApi_TopicDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MockApi_TopicDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rService.proto\032\017DataModel.proto\"\310\003\n\013Syn" +
      "cRequest\022&\n\tconfigure\030\001 \001(\0132\021.ConfigureR" +
      "equestH\000\022\'\n\nlocal_user\030\002 \001(\0132\021.LocalUser" +
      "RequestH\000\022\034\n\004auth\030\003 \001(\0132\014.AuthRequestH\000\022" +
      "-\n\rcontent_parse\030\004 \001(\0132\024.ContentParseReq" +
      "uestH\000\022-\n\rsubject_parse\030\005 \001(\0132\024.SubjectP" +
      "arseRequestH\000\0226\n\016mark_noti_read\030\006 \001(\0132\034." +
      "MarkNotificationReadRequestH\000\0226\n\022set_req" +
      "uest_option\030\007 \001(\0132\030.SetRequestOptionRequ" +
      "estH\000\0225\n\021invalidate_client\030\010 \001(\0132\030.Inval" +
      "idateClientRequestH\000\022<\n\025update_topic_pro" +
      "gress\030\t \001(\0132\033.UpdateTopicProgressRequest" +
      "H\000B\007\n\005value\"A\n\020ConfigureRequest\022\036\n\006confi" +
      "g\030\001 \001(\0132\016.Configuration\022\r\n\005debug\030\002 \001(\010\"1" +
      "\n\021ConfigureResponse\022\022\n\005error\030\001 \001(\tH\000\210\001\001B" +
      "\010\n\006_error\"#\n\020LocalUserRequest\022\017\n\007user_id" +
      "\030\001 \001(\t\"(\n\021LocalUserResponse\022\023\n\004user\030\001 \001(" +
      "\0132\005.User\"&\n\013AuthRequest\022\027\n\004info\030\001 \001(\0132\t." +
      "AuthInfo\"\016\n\014AuthResponse\"\"\n\023ContentParse" +
      "Request\022\013\n\003raw\030\001 \001(\t\"5\n\024ContentParseResp" +
      "onse\022\035\n\007content\030\001 \001(\0132\014.PostContent\"\"\n\023S" +
      "ubjectParseRequest\022\013\n\003raw\030\001 \001(\t\"1\n\024Subje" +
      "ctParseResponse\022\031\n\007subject\030\001 \001(\0132\010.Subje" +
      "ct\"8\n\033MarkNotificationReadRequest\022\013\n\003ids" +
      "\030\001 \003(\t\022\014\n\004read\030\002 \001(\010\"\036\n\034MarkNotification" +
      "ReadResponse\"9\n\027SetRequestOptionRequest\022" +
      "\036\n\006option\030\001 \001(\0132\016.RequestOption\"\032\n\030SetRe" +
      "questOptionResponse\"\\\n\032UpdateTopicProgre" +
      "ssRequest\022\020\n\010topic_id\030\001 \001(\t\022\025\n\rhighest_f" +
      "loor\030\002 \001(\r\022\025\n\rcurrent_floor\030\003 \001(\r\"\035\n\033Upd" +
      "ateTopicProgressResponse\"\312\014\n\014AsyncReques" +
      "t\022\'\n\ntopic_list\030\001 \001(\0132\021.TopicListRequest" +
      "H\000\022-\n\rtopic_details\030\002 \001(\0132\024.TopicDetails" +
      "RequestH\000\0221\n\017subforum_filter\030\003 \001(\0132\026.Sub" +
      "forumFilterRequestH\000\022\'\n\nforum_list\030\004 \001(\013" +
      "2\021.ForumListRequestH\000\022)\n\013remote_user\030\005 \001" +
      "(\0132\022.RemoteUserRequestH\000\022%\n\tpost_vote\030\006 " +
      "\001(\0132\020.PostVoteRequestH\000\022-\n\rtopic_history" +
      "\030\007 \001(\0132\024.TopicHistoryRequestH\000\022.\n\016hot_to" +
      "pic_list\030\010 \001(\0132\024.HotTopicListRequestH\000\022+" +
      "\n\014forum_search\030\t \001(\0132\023.ForumSearchReques" +
      "tH\000\0228\n\023favorite_topic_list\030\n \001(\0132\031.Favor" +
      "iteTopicListRequestH\000\022)\n\013topic_favor\030\013 \001" +
      "(\0132\022.TopicFavorRequestH\000\022A\n\030post_reply_f" +
      "etch_content\030\014 \001(\0132\035.PostReplyFetchConte" +
      "ntRequestH\000\022\'\n\npost_reply\030\r \001(\0132\021.PostRe" +
      "plyRequestH\000\0227\n\022fetch_notification\030\016 \001(\013" +
      "2\031.FetchNotificationRequestH\000\0225\n\021upload_" +
      "attachment\030\017 \001(\0132\030.UploadAttachmentReque" +
      "stH\000\0220\n\017user_topic_list\030\020 \001(\0132\025.UserTopi" +
      "cListRequestH\000\022.\n\016user_post_list\030\021 \001(\0132\024" +
      ".UserPostListRequestH\000\0226\n\022short_message_" +
      "list\030\022 \001(\0132\030.ShortMessageListRequestH\000\022<" +
      "\n\025short_message_details\030\023 \001(\0132\033.ShortMes" +
      "sageDetailsRequestH\000\0226\n\022short_message_po" +
      "st\030\024 \001(\0132\030.ShortMessagePostRequestH\000\022+\n\014" +
      "topic_search\030\025 \001(\0132\023.TopicSearchRequestH" +
      "\000\022#\n\010clock_in\030\026 \001(\0132\017.ClockInRequestH\000\022\036" +
      "\n\005cache\030\027 \001(\0132\r.CacheRequestH\000\022:\n\024favori" +
      "te_folder_list\030\030 \001(\0132\032.FavoriteFolderLis" +
      "tRequestH\000\022>\n\026favorite_folder_modify\030\031 \001" +
      "(\0132\034.FavoriteFolderModifyRequestH\000\022>\n\026fa" +
      "vorite_folder_create\030\032 \001(\0132\034.FavoriteFol" +
      "derCreateRequestH\000\022<\n\025user_signature_upd" +
      "ate\030\033 \001(\0132\033.UserSignatureUpdateRequestH\000" +
      "\0228\n\023favorite_forum_list\030\034 \001(\0132\031.Favorite" +
      "ForumListRequestH\000\022<\n\025favorite_forum_mod" +
      "ify\030\035 \001(\0132\033.FavoriteForumModifyRequestH\000" +
      "\022.\n\016clock_in_stats\030\036 \001(\0132\024.ClockInStatsR" +
      "equestH\000\022:\n\024delete_topic_history\030\037 \001(\0132\032" +
      ".DeleteTopicHistoryRequestH\000B\007\n\005value\"\267\001" +
      "\n\020TopicListRequest\022\024\n\002id\030\001 \001(\0132\010.ForumId" +
      "\022\014\n\004page\030\002 \001(\r\022\026\n\016sort_subforums\030\004 \001(\010\022&" +
      "\n\005order\030\005 \001(\0162\027.TopicListRequest.Order\022\030" +
      "\n\020recommended_only\030\006 \001(\010\"%\n\005Order\022\r\n\tLAS" +
      "T_POST\020\000\022\r\n\tPOST_DATE\020\001\"o\n\021TopicListResp" +
      "onse\022\025\n\005forum\030\004 \001(\0132\006.Forum\022\026\n\006topics\030\001 " +
      "\003(\0132\006.Topic\022\r\n\005pages\030\002 \001(\r\022\034\n\tsubforums\030" +
      "\003 \003(\0132\t.Subforum\"\237\002\n\023TopicDetailsRequest" +
      "\022\020\n\010topic_id\030\001 \001(\t\022\013\n\003fav\030\003 \001(\t\022\017\n\007post_" +
      "id\030\004 \001(\t\022\021\n\tauthor_id\030\005 \001(\t\022\035\n\025anonymous" +
      "_author_only\030\007 \001(\010\022\014\n\004page\030\002 \001(\r\022\023\n\013loca" +
      "l_cache\030\006 \001(\010\022=\n\020web_api_strategy\030\010 \001(\0162" +
      "#.TopicDetailsRequest.WebApiStrategy\"D\n\016" +
      "WebApiStrategy\022\014\n\010DISABLED\020\000\022\r\n\tSECONDAR" +
      "Y\020\001\022\013\n\007PRIMARY\020\002\022\010\n\004ONLY\020\003\"\335\001\n\024TopicDeta" +
      "ilsResponse\022\025\n\005topic\030\001 \001(\0132\006.Topic\022\026\n\007re" +
      "plies\030\002 \003(\0132\005.Post\022\022\n\nforum_name\030\004 \001(\t\022\r" +
      "\n\005pages\030\003 \001(\r\022\026\n\016is_local_cache\030\005 \001(\010\022\031\n" +
      "\014local_reason\030\007 \001(\tH\000\210\001\001\022\035\n\016in_place_use" +
      "rs\030\006 \003(\0132\005.User\022\020\n\010api_used\030\010 \001(\tB\017\n\r_lo" +
      "cal_reason\"\234\001\n\025SubforumFilterRequest\0223\n\t" +
      "operation\030\001 \001(\0162 .SubforumFilterRequest." +
      "Operation\022\020\n\010forum_id\030\002 \001(\t\022\032\n\022subforum_" +
      "filter_id\030\003 \001(\t\" \n\tOperation\022\010\n\004SHOW\020\000\022\t" +
      "\n\005BLOCK\020\001\"\030\n\026SubforumFilterResponse\"\022\n\020F" +
      "orumListRequest\"2\n\021ForumListResponse\022\035\n\n" +
      "categories\030\001 \003(\0132\t.Category\"7\n\021RemoteUse" +
      "rRequest\022\017\n\007user_id\030\001 \001(\t\022\021\n\tuser_name\030\002" +
      " \001(\t\"7\n\022RemoteUserResponse\022\030\n\004user\030\001 \001(\013" +
      "2\005.UserH\000\210\001\001B\007\n\005_user\"\201\001\n\017PostVoteReques" +
      "t\022-\n\toperation\030\001 \001(\0162\032.PostVoteRequest.O" +
      "peration\022\030\n\007post_id\030\002 \001(\0132\007.PostId\"%\n\tOp" +
      "eration\022\n\n\006UPVOTE\020\000\022\014\n\010DOWNVOTE\020\001\"Z\n\020Pos" +
      "tVoteResponse\022\r\n\005delta\030\001 \001(\021\022\022\n\005error\030\002 " +
      "\001(\tH\000\210\001\001\022\031\n\005state\030\003 \001(\0162\n.VoteStateB\010\n\006_" +
      "error\"$\n\023TopicHistoryRequest\022\r\n\005limit\030\001 " +
      "\001(\004\"6\n\024TopicHistoryResponse\022\036\n\006topics\030\001 " +
      "\003(\0132\016.TopicSnapshot\"-\n\031DeleteTopicHistor" +
      "yRequest\022\020\n\010topic_id\030\001 \001(\t\"-\n\032DeleteTopi" +
      "cHistoryResponse\022\017\n\007deleted\030\001 \001(\010\"\327\001\n\023Ho" +
      "tTopicListRequest\022\024\n\002id\030\001 \001(\0132\010.ForumId\022" +
      "-\n\005range\030\002 \001(\0162\036.HotTopicListRequest.Dat" +
      "eRange\022\035\n\020fetch_page_limit\030\003 \001(\rH\000\210\001\001\022\022\n" +
      "\005limit\030\004 \001(\004H\001\210\001\001\")\n\tDateRange\022\007\n\003DAY\020\000\022" +
      "\010\n\004WEEK\020\001\022\t\n\005MONTH\020\002B\023\n\021_fetch_page_limi" +
      "tB\010\n\006_limit\"E\n\024HotTopicListResponse\022\026\n\006t" +
      "opics\030\001 \003(\0132\006.Topic\022\025\n\005forum\030\002 \001(\0132\006.For" +
      "um\"!\n\022ForumSearchRequest\022\013\n\003key\030\001 \001(\t\"-\n" +
      "\023ForumSearchResponse\022\026\n\006forums\030\001 \003(\0132\006.F" +
      "orum\"\032\n\030FavoriteForumListRequest\"3\n\031Favo" +
      "riteForumListResponse\022\026\n\006forums\030\001 \003(\0132\006." +
      "Forum\"\213\001\n\032FavoriteForumModifyRequest\0228\n\t" +
      "operation\030\001 \001(\0162%.FavoriteForumModifyReq" +
      "uest.Operation\022\024\n\002id\030\002 \001(\0132\010.ForumId\"\035\n\t" +
      "Operation\022\007\n\003ADD\020\000\022\007\n\003DEL\020\001\"\035\n\033FavoriteF" +
      "orumModifyResponse\";\n\030FavoriteTopicListR" +
      "equest\022\014\n\004page\030\001 \001(\r\022\021\n\tfolder_id\030\002 \001(\t\"" +
      "B\n\031FavoriteTopicListResponse\022\026\n\006topics\030\001" +
      " \003(\0132\006.Topic\022\r\n\005pages\030\002 \001(\r\"\033\n\031FavoriteF" +
      "olderListRequest\"C\n\032FavoriteFolderListRe" +
      "sponse\022%\n\007folders\030\001 \003(\0132\024.FavoriteTopicF" +
      "older\"u\n\033FavoriteFolderModifyRequest\022\021\n\t" +
      "folder_id\030\001 \001(\t\022\020\n\006rename\030\002 \001(\tH\000\022\025\n\013set" +
      "_default\030\003 \001(\010H\000\022\020\n\006delete\030\004 \001(\010H\000B\010\n\006ch" +
      "ange\"\036\n\034FavoriteFolderModifyResponse\"@\n\033" +
      "FavoriteFolderCreateRequest\022\014\n\004name\030\001 \001(" +
      "\t\022\023\n\013set_default\030\002 \001(\010\"1\n\034FavoriteFolder" +
      "CreateResponse\022\021\n\tfolder_id\030\001 \001(\t\"\213\001\n\021To" +
      "picFavorRequest\022\020\n\010topic_id\030\001 \001(\t\022/\n\tope" +
      "ration\030\002 \001(\0162\034.TopicFavorRequest.Operati" +
      "on\022\021\n\tfolder_id\030\003 \001(\t\" \n\tOperation\022\007\n\003AD" +
      "D\020\000\022\n\n\006DELETE\020\001\"<\n\022TopicFavorResponse\022\022\n" +
      "\nis_favored\030\001 \001(\010\022\022\n\nfolder_ids\030\002 \003(\t\"@\n" +
      "\034PostReplyFetchContentRequest\022 \n\006action\030" +
      "\001 \001(\0132\020.PostReplyAction\"x\n\035PostReplyFetc" +
      "hContentResponse\022\017\n\007content\030\001 \001(\t\022\024\n\007sub" +
      "ject\030\002 \001(\tH\000\210\001\001\022$\n\010verbatim\030\003 \001(\0132\022.Post" +
      "ReplyVerbatimB\n\n\010_subject\"\240\001\n\020PostReplyR" +
      "equest\022 \n\006action\030\001 \001(\0132\020.PostReplyAction" +
      "\022\017\n\007content\030\002 \001(\t\022\024\n\007subject\030\003 \001(\tH\000\210\001\001\022" +
      "$\n\013attachments\030\004 \003(\0132\017.PostAttachment\022\021\n" +
      "\tanonymous\030\005 \001(\010B\n\n\010_subject\"$\n\021PostRepl" +
      "yResponse\022\017\n\007message\030\001 \001(\t\"\032\n\030FetchNotif" +
      "icationRequest\"9\n\031FetchNotificationRespo" +
      "nse\022\034\n\005notis\030\001 \003(\0132\r.Notification\"I\n\027Upl" +
      "oadAttachmentRequest\022 \n\006action\030\001 \001(\0132\020.P" +
      "ostReplyAction\022\014\n\004file\030\002 \001(\014\"?\n\030UploadAt" +
      "tachmentResponse\022#\n\nattachment\030\001 \001(\0132\017.P" +
      "ostAttachment\"7\n\024UserTopicListRequest\022\021\n" +
      "\tauthor_id\030\001 \001(\t\022\014\n\004page\030\002 \001(\r\">\n\025UserTo" +
      "picListResponse\022\026\n\006topics\030\001 \003(\0132\006.Topic\022" +
      "\r\n\005pages\030\002 \001(\r\"6\n\023UserPostListRequest\022\021\n" +
      "\tauthor_id\030\001 \001(\t\022\014\n\004page\030\002 \001(\r\"8\n\024UserPo" +
      "stListResponse\022 \n\003tps\030\001 \003(\0132\023.TopicWithL" +
      "ightPost\"\'\n\027ShortMessageListRequest\022\014\n\004p" +
      "age\030\001 \001(\r\"J\n\030ShortMessageListResponse\022\037\n" +
      "\010messages\030\001 \003(\0132\r.ShortMessage\022\r\n\005pages\030" +
      "\002 \001(\r\"6\n\032ShortMessageDetailsRequest\022\n\n\002i" +
      "d\030\001 \001(\t\022\014\n\004page\030\002 \001(\r\"d\n\033ShortMessageDet" +
      "ailsResponse\022 \n\005posts\030\001 \003(\0132\021.ShortMessa" +
      "gePost\022\r\n\005pages\030\002 \001(\r\022\024\n\005users\030\003 \003(\0132\005.U" +
      "ser\"p\n\027ShortMessagePostRequest\022\'\n\006action" +
      "\030\001 \001(\0132\027.ShortMessagePostAction\022\017\n\007conte" +
      "nt\030\002 \001(\t\022\017\n\007subject\030\003 \001(\t\022\n\n\002to\030\004 \003(\t\"\032\n" +
      "\030ShortMessagePostResponse\"/\n\032UserSignatu" +
      "reUpdateRequest\022\021\n\tsignature\030\001 \001(\t\"\035\n\033Us" +
      "erSignatureUpdateResponse\"w\n\022TopicSearch" +
      "Request\022\024\n\002id\030\001 \001(\0132\010.ForumId\022\014\n\004page\030\002 " +
      "\001(\r\022\026\n\016search_content\030\003 \001(\010\022\030\n\020recommend" +
      "ed_only\030\004 \001(\010\022\013\n\003key\030\005 \001(\t\"<\n\023TopicSearc" +
      "hResponse\022\026\n\006topics\030\001 \003(\0132\006.Topic\022\r\n\005pag" +
      "es\030\002 \001(\r\"\020\n\016ClockInRequest\"\025\n\023ClockInSta" +
      "tsRequest\"\203\001\n\024ClockInStatsResponse\022\014\n\004da" +
      "te\030\001 \001(\t\022\026\n\016continued_days\030\002 \001(\005\022\022\n\ntota" +
      "l_days\030\003 \001(\005\022\r\n\005money\030\004 \001(\005\022\017\n\007money_n\030\005" +
      " \001(\005\022\021\n\tlast_time\030\006 \001(\003\"\225\001\n\017ClockInRespo" +
      "nse\022\014\n\004date\030\001 \001(\t\022\025\n\ris_first_time\030\002 \001(\010" +
      "\022\026\n\016continued_days\030\003 \001(\005\022\022\n\ntotal_days\030\004" +
      " \001(\005\022\r\n\005money\030\005 \001(\005\022\017\n\007money_n\030\006 \001(\005\022\021\n\t" +
      "last_time\030\007 \001(\003\"L\n\014CacheRequest\022\030\n\004type\030" +
      "\001 \001(\0162\n.CacheType\022\"\n\toperation\030\002 \001(\0162\017.C" +
      "acheOperation\"2\n\rCacheResponse\022\r\n\005items\030" +
      "\001 \001(\004\022\022\n\ntotal_size\030\002 \001(\004\"\031\n\027InvalidateC" +
      "lientRequest\"\032\n\030InvalidateClientResponse" +
      "\"\241\001\n\007MockApi\022(\n\ntopic_list\030\001 \001(\0132\022.MockA" +
      "pi.TopicListH\000\022.\n\rtopic_details\030\002 \001(\0132\025." +
      "MockApi.TopicDetailsH\000\032\027\n\tTopicList\022\n\n\002i" +
      "d\030\001 \001(\t\032\032\n\014TopicDetails\022\n\n\002id\030\001 \001(\tB\007\n\005v" +
      "alueB%\n!com.bugenzhao.mnga.protos.servic" +
      "eP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.bugenzhao.mnga.protos.datamodel.DataModel.getDescriptor(),
        });
    internal_static_SyncRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_SyncRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SyncRequest_descriptor,
        new java.lang.String[] { "Configure", "LocalUser", "Auth", "ContentParse", "SubjectParse", "MarkNotiRead", "SetRequestOption", "InvalidateClient", "UpdateTopicProgress", "Value", });
    internal_static_ConfigureRequest_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_ConfigureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ConfigureRequest_descriptor,
        new java.lang.String[] { "Config", "Debug", });
    internal_static_ConfigureResponse_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_ConfigureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ConfigureResponse_descriptor,
        new java.lang.String[] { "Error", });
    internal_static_LocalUserRequest_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_LocalUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_LocalUserRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_LocalUserResponse_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_LocalUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_LocalUserResponse_descriptor,
        new java.lang.String[] { "User", });
    internal_static_AuthRequest_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_AuthRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AuthRequest_descriptor,
        new java.lang.String[] { "Info", });
    internal_static_AuthResponse_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_AuthResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AuthResponse_descriptor,
        new java.lang.String[] { });
    internal_static_ContentParseRequest_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_ContentParseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ContentParseRequest_descriptor,
        new java.lang.String[] { "Raw", });
    internal_static_ContentParseResponse_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_ContentParseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ContentParseResponse_descriptor,
        new java.lang.String[] { "Content", });
    internal_static_SubjectParseRequest_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_SubjectParseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SubjectParseRequest_descriptor,
        new java.lang.String[] { "Raw", });
    internal_static_SubjectParseResponse_descriptor =
      getDescriptor().getMessageType(10);
    internal_static_SubjectParseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SubjectParseResponse_descriptor,
        new java.lang.String[] { "Subject", });
    internal_static_MarkNotificationReadRequest_descriptor =
      getDescriptor().getMessageType(11);
    internal_static_MarkNotificationReadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MarkNotificationReadRequest_descriptor,
        new java.lang.String[] { "Ids", "Read", });
    internal_static_MarkNotificationReadResponse_descriptor =
      getDescriptor().getMessageType(12);
    internal_static_MarkNotificationReadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MarkNotificationReadResponse_descriptor,
        new java.lang.String[] { });
    internal_static_SetRequestOptionRequest_descriptor =
      getDescriptor().getMessageType(13);
    internal_static_SetRequestOptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SetRequestOptionRequest_descriptor,
        new java.lang.String[] { "Option", });
    internal_static_SetRequestOptionResponse_descriptor =
      getDescriptor().getMessageType(14);
    internal_static_SetRequestOptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SetRequestOptionResponse_descriptor,
        new java.lang.String[] { });
    internal_static_UpdateTopicProgressRequest_descriptor =
      getDescriptor().getMessageType(15);
    internal_static_UpdateTopicProgressRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UpdateTopicProgressRequest_descriptor,
        new java.lang.String[] { "TopicId", "HighestFloor", "CurrentFloor", });
    internal_static_UpdateTopicProgressResponse_descriptor =
      getDescriptor().getMessageType(16);
    internal_static_UpdateTopicProgressResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UpdateTopicProgressResponse_descriptor,
        new java.lang.String[] { });
    internal_static_AsyncRequest_descriptor =
      getDescriptor().getMessageType(17);
    internal_static_AsyncRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AsyncRequest_descriptor,
        new java.lang.String[] { "TopicList", "TopicDetails", "SubforumFilter", "ForumList", "RemoteUser", "PostVote", "TopicHistory", "HotTopicList", "ForumSearch", "FavoriteTopicList", "TopicFavor", "PostReplyFetchContent", "PostReply", "FetchNotification", "UploadAttachment", "UserTopicList", "UserPostList", "ShortMessageList", "ShortMessageDetails", "ShortMessagePost", "TopicSearch", "ClockIn", "Cache", "FavoriteFolderList", "FavoriteFolderModify", "FavoriteFolderCreate", "UserSignatureUpdate", "FavoriteForumList", "FavoriteForumModify", "ClockInStats", "DeleteTopicHistory", "Value", });
    internal_static_TopicListRequest_descriptor =
      getDescriptor().getMessageType(18);
    internal_static_TopicListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TopicListRequest_descriptor,
        new java.lang.String[] { "Id", "Page", "SortSubforums", "Order", "RecommendedOnly", });
    internal_static_TopicListResponse_descriptor =
      getDescriptor().getMessageType(19);
    internal_static_TopicListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TopicListResponse_descriptor,
        new java.lang.String[] { "Forum", "Topics", "Pages", "Subforums", });
    internal_static_TopicDetailsRequest_descriptor =
      getDescriptor().getMessageType(20);
    internal_static_TopicDetailsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TopicDetailsRequest_descriptor,
        new java.lang.String[] { "TopicId", "Fav", "PostId", "AuthorId", "AnonymousAuthorOnly", "Page", "LocalCache", "WebApiStrategy", });
    internal_static_TopicDetailsResponse_descriptor =
      getDescriptor().getMessageType(21);
    internal_static_TopicDetailsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TopicDetailsResponse_descriptor,
        new java.lang.String[] { "Topic", "Replies", "ForumName", "Pages", "IsLocalCache", "LocalReason", "InPlaceUsers", "ApiUsed", });
    internal_static_SubforumFilterRequest_descriptor =
      getDescriptor().getMessageType(22);
    internal_static_SubforumFilterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SubforumFilterRequest_descriptor,
        new java.lang.String[] { "Operation", "ForumId", "SubforumFilterId", });
    internal_static_SubforumFilterResponse_descriptor =
      getDescriptor().getMessageType(23);
    internal_static_SubforumFilterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SubforumFilterResponse_descriptor,
        new java.lang.String[] { });
    internal_static_ForumListRequest_descriptor =
      getDescriptor().getMessageType(24);
    internal_static_ForumListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ForumListRequest_descriptor,
        new java.lang.String[] { });
    internal_static_ForumListResponse_descriptor =
      getDescriptor().getMessageType(25);
    internal_static_ForumListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ForumListResponse_descriptor,
        new java.lang.String[] { "Categories", });
    internal_static_RemoteUserRequest_descriptor =
      getDescriptor().getMessageType(26);
    internal_static_RemoteUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RemoteUserRequest_descriptor,
        new java.lang.String[] { "UserId", "UserName", });
    internal_static_RemoteUserResponse_descriptor =
      getDescriptor().getMessageType(27);
    internal_static_RemoteUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RemoteUserResponse_descriptor,
        new java.lang.String[] { "User", });
    internal_static_PostVoteRequest_descriptor =
      getDescriptor().getMessageType(28);
    internal_static_PostVoteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PostVoteRequest_descriptor,
        new java.lang.String[] { "Operation", "PostId", });
    internal_static_PostVoteResponse_descriptor =
      getDescriptor().getMessageType(29);
    internal_static_PostVoteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PostVoteResponse_descriptor,
        new java.lang.String[] { "Delta", "Error", "State", });
    internal_static_TopicHistoryRequest_descriptor =
      getDescriptor().getMessageType(30);
    internal_static_TopicHistoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TopicHistoryRequest_descriptor,
        new java.lang.String[] { "Limit", });
    internal_static_TopicHistoryResponse_descriptor =
      getDescriptor().getMessageType(31);
    internal_static_TopicHistoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TopicHistoryResponse_descriptor,
        new java.lang.String[] { "Topics", });
    internal_static_DeleteTopicHistoryRequest_descriptor =
      getDescriptor().getMessageType(32);
    internal_static_DeleteTopicHistoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DeleteTopicHistoryRequest_descriptor,
        new java.lang.String[] { "TopicId", });
    internal_static_DeleteTopicHistoryResponse_descriptor =
      getDescriptor().getMessageType(33);
    internal_static_DeleteTopicHistoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DeleteTopicHistoryResponse_descriptor,
        new java.lang.String[] { "Deleted", });
    internal_static_HotTopicListRequest_descriptor =
      getDescriptor().getMessageType(34);
    internal_static_HotTopicListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_HotTopicListRequest_descriptor,
        new java.lang.String[] { "Id", "Range", "FetchPageLimit", "Limit", });
    internal_static_HotTopicListResponse_descriptor =
      getDescriptor().getMessageType(35);
    internal_static_HotTopicListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_HotTopicListResponse_descriptor,
        new java.lang.String[] { "Topics", "Forum", });
    internal_static_ForumSearchRequest_descriptor =
      getDescriptor().getMessageType(36);
    internal_static_ForumSearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ForumSearchRequest_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_ForumSearchResponse_descriptor =
      getDescriptor().getMessageType(37);
    internal_static_ForumSearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ForumSearchResponse_descriptor,
        new java.lang.String[] { "Forums", });
    internal_static_FavoriteForumListRequest_descriptor =
      getDescriptor().getMessageType(38);
    internal_static_FavoriteForumListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FavoriteForumListRequest_descriptor,
        new java.lang.String[] { });
    internal_static_FavoriteForumListResponse_descriptor =
      getDescriptor().getMessageType(39);
    internal_static_FavoriteForumListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FavoriteForumListResponse_descriptor,
        new java.lang.String[] { "Forums", });
    internal_static_FavoriteForumModifyRequest_descriptor =
      getDescriptor().getMessageType(40);
    internal_static_FavoriteForumModifyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FavoriteForumModifyRequest_descriptor,
        new java.lang.String[] { "Operation", "Id", });
    internal_static_FavoriteForumModifyResponse_descriptor =
      getDescriptor().getMessageType(41);
    internal_static_FavoriteForumModifyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FavoriteForumModifyResponse_descriptor,
        new java.lang.String[] { });
    internal_static_FavoriteTopicListRequest_descriptor =
      getDescriptor().getMessageType(42);
    internal_static_FavoriteTopicListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FavoriteTopicListRequest_descriptor,
        new java.lang.String[] { "Page", "FolderId", });
    internal_static_FavoriteTopicListResponse_descriptor =
      getDescriptor().getMessageType(43);
    internal_static_FavoriteTopicListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FavoriteTopicListResponse_descriptor,
        new java.lang.String[] { "Topics", "Pages", });
    internal_static_FavoriteFolderListRequest_descriptor =
      getDescriptor().getMessageType(44);
    internal_static_FavoriteFolderListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FavoriteFolderListRequest_descriptor,
        new java.lang.String[] { });
    internal_static_FavoriteFolderListResponse_descriptor =
      getDescriptor().getMessageType(45);
    internal_static_FavoriteFolderListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FavoriteFolderListResponse_descriptor,
        new java.lang.String[] { "Folders", });
    internal_static_FavoriteFolderModifyRequest_descriptor =
      getDescriptor().getMessageType(46);
    internal_static_FavoriteFolderModifyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FavoriteFolderModifyRequest_descriptor,
        new java.lang.String[] { "FolderId", "Rename", "SetDefault", "Delete", "Change", });
    internal_static_FavoriteFolderModifyResponse_descriptor =
      getDescriptor().getMessageType(47);
    internal_static_FavoriteFolderModifyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FavoriteFolderModifyResponse_descriptor,
        new java.lang.String[] { });
    internal_static_FavoriteFolderCreateRequest_descriptor =
      getDescriptor().getMessageType(48);
    internal_static_FavoriteFolderCreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FavoriteFolderCreateRequest_descriptor,
        new java.lang.String[] { "Name", "SetDefault", });
    internal_static_FavoriteFolderCreateResponse_descriptor =
      getDescriptor().getMessageType(49);
    internal_static_FavoriteFolderCreateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FavoriteFolderCreateResponse_descriptor,
        new java.lang.String[] { "FolderId", });
    internal_static_TopicFavorRequest_descriptor =
      getDescriptor().getMessageType(50);
    internal_static_TopicFavorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TopicFavorRequest_descriptor,
        new java.lang.String[] { "TopicId", "Operation", "FolderId", });
    internal_static_TopicFavorResponse_descriptor =
      getDescriptor().getMessageType(51);
    internal_static_TopicFavorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TopicFavorResponse_descriptor,
        new java.lang.String[] { "IsFavored", "FolderIds", });
    internal_static_PostReplyFetchContentRequest_descriptor =
      getDescriptor().getMessageType(52);
    internal_static_PostReplyFetchContentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PostReplyFetchContentRequest_descriptor,
        new java.lang.String[] { "Action", });
    internal_static_PostReplyFetchContentResponse_descriptor =
      getDescriptor().getMessageType(53);
    internal_static_PostReplyFetchContentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PostReplyFetchContentResponse_descriptor,
        new java.lang.String[] { "Content", "Subject", "Verbatim", });
    internal_static_PostReplyRequest_descriptor =
      getDescriptor().getMessageType(54);
    internal_static_PostReplyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PostReplyRequest_descriptor,
        new java.lang.String[] { "Action", "Content", "Subject", "Attachments", "Anonymous", });
    internal_static_PostReplyResponse_descriptor =
      getDescriptor().getMessageType(55);
    internal_static_PostReplyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PostReplyResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_FetchNotificationRequest_descriptor =
      getDescriptor().getMessageType(56);
    internal_static_FetchNotificationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FetchNotificationRequest_descriptor,
        new java.lang.String[] { });
    internal_static_FetchNotificationResponse_descriptor =
      getDescriptor().getMessageType(57);
    internal_static_FetchNotificationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FetchNotificationResponse_descriptor,
        new java.lang.String[] { "Notis", });
    internal_static_UploadAttachmentRequest_descriptor =
      getDescriptor().getMessageType(58);
    internal_static_UploadAttachmentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UploadAttachmentRequest_descriptor,
        new java.lang.String[] { "Action", "File", });
    internal_static_UploadAttachmentResponse_descriptor =
      getDescriptor().getMessageType(59);
    internal_static_UploadAttachmentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UploadAttachmentResponse_descriptor,
        new java.lang.String[] { "Attachment", });
    internal_static_UserTopicListRequest_descriptor =
      getDescriptor().getMessageType(60);
    internal_static_UserTopicListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UserTopicListRequest_descriptor,
        new java.lang.String[] { "AuthorId", "Page", });
    internal_static_UserTopicListResponse_descriptor =
      getDescriptor().getMessageType(61);
    internal_static_UserTopicListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UserTopicListResponse_descriptor,
        new java.lang.String[] { "Topics", "Pages", });
    internal_static_UserPostListRequest_descriptor =
      getDescriptor().getMessageType(62);
    internal_static_UserPostListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UserPostListRequest_descriptor,
        new java.lang.String[] { "AuthorId", "Page", });
    internal_static_UserPostListResponse_descriptor =
      getDescriptor().getMessageType(63);
    internal_static_UserPostListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UserPostListResponse_descriptor,
        new java.lang.String[] { "Tps", });
    internal_static_ShortMessageListRequest_descriptor =
      getDescriptor().getMessageType(64);
    internal_static_ShortMessageListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ShortMessageListRequest_descriptor,
        new java.lang.String[] { "Page", });
    internal_static_ShortMessageListResponse_descriptor =
      getDescriptor().getMessageType(65);
    internal_static_ShortMessageListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ShortMessageListResponse_descriptor,
        new java.lang.String[] { "Messages", "Pages", });
    internal_static_ShortMessageDetailsRequest_descriptor =
      getDescriptor().getMessageType(66);
    internal_static_ShortMessageDetailsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ShortMessageDetailsRequest_descriptor,
        new java.lang.String[] { "Id", "Page", });
    internal_static_ShortMessageDetailsResponse_descriptor =
      getDescriptor().getMessageType(67);
    internal_static_ShortMessageDetailsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ShortMessageDetailsResponse_descriptor,
        new java.lang.String[] { "Posts", "Pages", "Users", });
    internal_static_ShortMessagePostRequest_descriptor =
      getDescriptor().getMessageType(68);
    internal_static_ShortMessagePostRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ShortMessagePostRequest_descriptor,
        new java.lang.String[] { "Action", "Content", "Subject", "To", });
    internal_static_ShortMessagePostResponse_descriptor =
      getDescriptor().getMessageType(69);
    internal_static_ShortMessagePostResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ShortMessagePostResponse_descriptor,
        new java.lang.String[] { });
    internal_static_UserSignatureUpdateRequest_descriptor =
      getDescriptor().getMessageType(70);
    internal_static_UserSignatureUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UserSignatureUpdateRequest_descriptor,
        new java.lang.String[] { "Signature", });
    internal_static_UserSignatureUpdateResponse_descriptor =
      getDescriptor().getMessageType(71);
    internal_static_UserSignatureUpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UserSignatureUpdateResponse_descriptor,
        new java.lang.String[] { });
    internal_static_TopicSearchRequest_descriptor =
      getDescriptor().getMessageType(72);
    internal_static_TopicSearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TopicSearchRequest_descriptor,
        new java.lang.String[] { "Id", "Page", "SearchContent", "RecommendedOnly", "Key", });
    internal_static_TopicSearchResponse_descriptor =
      getDescriptor().getMessageType(73);
    internal_static_TopicSearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TopicSearchResponse_descriptor,
        new java.lang.String[] { "Topics", "Pages", });
    internal_static_ClockInRequest_descriptor =
      getDescriptor().getMessageType(74);
    internal_static_ClockInRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ClockInRequest_descriptor,
        new java.lang.String[] { });
    internal_static_ClockInStatsRequest_descriptor =
      getDescriptor().getMessageType(75);
    internal_static_ClockInStatsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ClockInStatsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_ClockInStatsResponse_descriptor =
      getDescriptor().getMessageType(76);
    internal_static_ClockInStatsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ClockInStatsResponse_descriptor,
        new java.lang.String[] { "Date", "ContinuedDays", "TotalDays", "Money", "MoneyN", "LastTime", });
    internal_static_ClockInResponse_descriptor =
      getDescriptor().getMessageType(77);
    internal_static_ClockInResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ClockInResponse_descriptor,
        new java.lang.String[] { "Date", "IsFirstTime", "ContinuedDays", "TotalDays", "Money", "MoneyN", "LastTime", });
    internal_static_CacheRequest_descriptor =
      getDescriptor().getMessageType(78);
    internal_static_CacheRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CacheRequest_descriptor,
        new java.lang.String[] { "Type", "Operation", });
    internal_static_CacheResponse_descriptor =
      getDescriptor().getMessageType(79);
    internal_static_CacheResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CacheResponse_descriptor,
        new java.lang.String[] { "Items", "TotalSize", });
    internal_static_InvalidateClientRequest_descriptor =
      getDescriptor().getMessageType(80);
    internal_static_InvalidateClientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_InvalidateClientRequest_descriptor,
        new java.lang.String[] { });
    internal_static_InvalidateClientResponse_descriptor =
      getDescriptor().getMessageType(81);
    internal_static_InvalidateClientResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_InvalidateClientResponse_descriptor,
        new java.lang.String[] { });
    internal_static_MockApi_descriptor =
      getDescriptor().getMessageType(82);
    internal_static_MockApi_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MockApi_descriptor,
        new java.lang.String[] { "TopicList", "TopicDetails", "Value", });
    internal_static_MockApi_TopicList_descriptor =
      internal_static_MockApi_descriptor.getNestedType(0);
    internal_static_MockApi_TopicList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MockApi_TopicList_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_MockApi_TopicDetails_descriptor =
      internal_static_MockApi_descriptor.getNestedType(1);
    internal_static_MockApi_TopicDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MockApi_TopicDetails_descriptor,
        new java.lang.String[] { "Id", });
    descriptor.resolveAllFeaturesImmutable();
    com.bugenzhao.mnga.protos.datamodel.DataModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
